// Generated by LiveScript 1.2.0
(function(){
  $(function(){
    var ns_member;
    ns_member = {};
    ns_member.waterflow = function(){
      var option;
      option = {
        colMinWidth: $('.member').width(),
        defaultContainerWidth: $('#member-list').width(),
        autoresize: true
      };
      $('#member-list').addClass('waterfall');
      $('.waterfall').waterfall(option);
    };
    ns_member.waterflow();
  });
}).call(this);
